### PR TITLE
Phase 1 jQuery-ui features replace.

### PR DESCRIPTION
**Pull request by sjpadgett**
- draggable and resizable replacement
- made global in utils.js. just add drag-resize class anywhere drag/resize is needed.
- library is self loading on demand if Header class is used in script.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@tywrenn Just a few files. Take a look for any conflicts in you current work before I push this to @bradymiller. Then I hope he can give me a better idea of other jquery-ui features we use.

**Comment by sjpadgett** [comment]
@bradymiller Added some more to our js utilities. Also showed a use case example for our new js translation function xl(). That is probably one of the better things we've done all year and will prove to be invaluable once folks get use to using it. No more being forced to php to xlate with our ever growing js.
I don't think I could have made draggable and resize any easier. Just add a class (drag-resize) to any element and you're good to go.
Are we having fun yet?

**Comment by bradymiller** [comment]
@sjpadgett , nice stuff!!

**Comment by bradymiller** [comment]
And of course the OpenEMR fan club is cheering:
2DV

**Pull request merged**
